DROP TABLE IF EXISTS MEDICATION;
DROP TABLE IF EXISTS BATCH;

CREATE TABLE MEDICATION
(
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    form VARCHAR(50),
    strength VARCHAR(50)
);

CREATE TABLE BATCH
(
    batch_no VARCHAR(36) PRIMARY KEY,
    med_id   VARCHAR(36) NOT NULL,
    quantity INT NOT NULL,
    expiry   DATE NOT NULL,

    CONSTRAINT fk_medication
        FOREIGN KEY (med_id) REFERENCES MEDICATION(id)
            ON DELETE CASCADE
);
